services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_api
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/iss_over_earthquakes_db
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: